#############################################################################
# Makefile for building: build/Chess_Project.app/Contents/MacOS/Chess_Project
# Generated by qmake (3.1) (Qt 6.9.1)
# Project:  Chess_Project.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile Chess_Project.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk -mmacosx-version-min=14.0 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk -mmacosx-version-min=14.0 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I. -Iinclude -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -Ibuild/moc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/System/Library/Frameworks/AGL.framework/Headers -Ibuild/ui -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/share/qt/mkspecs/macx-clang -F/usr/local/lib
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Chess_Project1.0.0
DISTDIR = /Users/zakariazair/Desktop/personal_projects/qt_board_game/build/objs/Chess_Project1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk -mmacosx-version-min=14.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/usr/local/lib
LIBS          = $(SUBLIBS) -F/usr/local/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework UniformTypeIdentifiers -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/objs/

####### Files

SOURCES       = src/Case.cpp \
		src/Cavalier.cpp \
		src/Jeux.cpp \
		src/Joueur.cpp \
		src/main.cpp \
		src/Piece.cpp \
		src/ProjetFinalEchec.cpp \
		src/Roi.cpp \
		src/Tour.cpp build/moc/moc_ProjetFinalEchec.cpp
OBJECTS       = build/objs/Case.o \
		build/objs/Cavalier.o \
		build/objs/Jeux.o \
		build/objs/Joueur.o \
		build/objs/main.o \
		build/objs/Piece.o \
		build/objs/ProjetFinalEchec.o \
		build/objs/Roi.o \
		build/objs/Tour.o \
		build/objs/moc_ProjetFinalEchec.o
DIST          = /usr/local/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/share/qt/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/share/qt/mkspecs/qconfig.pri \
		/usr/local/share/qt/mkspecs/modules/qt_ext_openxr_loader.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquicklogic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquicklogic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene3d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene3d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_connectivity_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_graphs.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_graphs_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_graphswidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_graphswidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_grpc.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_grpc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_grpcquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_grpcquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_httpserver_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_protobuf.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_protobuf_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_protobufquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_protobufquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dxr.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlglobal_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboardqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboardqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/usr/local/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/share/qt/mkspecs/features/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/share/qt/mkspecs/features/permissions.prf \
		/usr/local/share/qt/mkspecs/features/qt.prf \
		/usr/local/share/qt/mkspecs/features/resources_functions.prf \
		/usr/local/share/qt/mkspecs/features/resources.prf \
		/usr/local/share/qt/mkspecs/features/moc.prf \
		/usr/local/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/local/share/qt/mkspecs/features/uic.prf \
		/usr/local/share/qt/mkspecs/features/unix/thread.prf \
		/usr/local/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/share/qt/mkspecs/features/yacc.prf \
		/usr/local/share/qt/mkspecs/features/lex.prf \
		Chess_Project.pro include/Case.h \
		include/Cavalier.h \
		include/Jeux.h \
		include/Joueur.h \
		include/Piece.h \
		include/ProjetFinalEchec.h \
		include/Roi.h \
		include/Tour.h src/Case.cpp \
		src/Cavalier.cpp \
		src/Jeux.cpp \
		src/Joueur.cpp \
		src/main.cpp \
		src/Piece.cpp \
		src/ProjetFinalEchec.cpp \
		src/Roi.cpp \
		src/Tour.cpp
QMAKE_TARGET  = Chess_Project
DESTDIR       = build/
TARGET        = build/Chess_Project.app/Contents/MacOS/Chess_Project

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 15.5
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/zakariazair/Desktop/personal_projects/qt_board_game/.qmake.stash
EXPORT_VALID_ARCHS = x86_64
EXPORT_DEFAULT_ARCHS = x86_64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/zakariazair/Desktop/personal_projects/qt_board_game/Chess_Project.pro


include /usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

build/Chess_Project.app/Contents/MacOS/Chess_Project: build/ui/ui_ProjetFinalEchec.h $(OBJECTS)  
	@test -d build/Chess_Project.app/Contents/MacOS/ || mkdir -p build/Chess_Project.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Chess_Project.pro /usr/local/share/qt/mkspecs/macx-clang/qmake.conf /usr/local/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/share/qt/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/share/qt/mkspecs/qconfig.pri \
		/usr/local/share/qt/mkspecs/modules/qt_ext_openxr_loader.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquicklogic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquicklogic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene3d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene3d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_connectivity_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_graphs.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_graphs_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_graphswidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_graphswidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_grpc.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_grpc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_grpcquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_grpcquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_httpserver_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_protobuf.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_protobuf_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_protobufquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_protobufquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dxr.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlglobal_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboardqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboardqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		/usr/local/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/share/qt/mkspecs/features/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/share/qt/mkspecs/features/permissions.prf \
		/usr/local/share/qt/mkspecs/features/qt.prf \
		/usr/local/share/qt/mkspecs/features/resources_functions.prf \
		/usr/local/share/qt/mkspecs/features/resources.prf \
		/usr/local/share/qt/mkspecs/features/moc.prf \
		/usr/local/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/local/share/qt/mkspecs/features/uic.prf \
		/usr/local/share/qt/mkspecs/features/unix/thread.prf \
		/usr/local/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/share/qt/mkspecs/features/yacc.prf \
		/usr/local/share/qt/mkspecs/features/lex.prf \
		Chess_Project.pro \
		/usr/local/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/usr/local/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile Chess_Project.pro
/usr/local/share/qt/mkspecs/features/spec_pre.prf:
/usr/local/share/qt/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/6.9.1/share/qt/mkspecs/common/clang-mac.conf:
/usr/local/share/qt/mkspecs/qconfig.pri:
/usr/local/share/qt/mkspecs/modules/qt_ext_openxr_loader.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquicklogic.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquicklogic_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene3d.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3dquickscene3d_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_charts.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_chartsqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_coap.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_coap_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_connectivity_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_graphs.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_graphs_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_graphswidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_graphswidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_grpc.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_grpc_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_grpcquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_grpcquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_help.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_httpserver.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_httpserver_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_jsonrpc_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsplatform.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsplatform_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_languageserver_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_linguist.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_location.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_network.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opcua.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opcua_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_pdf.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_pdfquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_pdfquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_protobuf.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_protobuf_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_protobufquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_protobufquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlformat_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlls_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmeta.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmeta_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlnetwork.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dphysics.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dxr.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick3dxr_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickeffects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickeffects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimage.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlglobal_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testinternals_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_tools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboardqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboardqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webchannelquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webchannelquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webview.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_webviewquick_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/local/share/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
/usr/local/share/qt/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
/usr/local/share/qt/mkspecs/features/qt_functions.prf:
/usr/local/share/qt/mkspecs/features/qt_config.prf:
/usr/local/share/qt/mkspecs/macx-clang/qmake.conf:
/usr/local/share/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/local/share/qt/mkspecs/features/mac/sdk.prf:
/usr/local/share/qt/mkspecs/features/toolchain.prf:
/usr/local/share/qt/mkspecs/features/mac/toolchain.prf:
/usr/local/share/qt/mkspecs/features/default_pre.prf:
/usr/local/share/qt/mkspecs/features/mac/default_pre.prf:
/usr/local/share/qt/mkspecs/features/resolve_config.prf:
/usr/local/share/qt/mkspecs/features/default_post.prf:
/usr/local/share/qt/mkspecs/features/mac/default_post.prf:
/usr/local/share/qt/mkspecs/features/mac/objective_c.prf:
/usr/local/share/qt/mkspecs/features/mac/mac.prf:
/usr/local/share/qt/mkspecs/features/warn_on.prf:
/usr/local/share/qt/mkspecs/features/permissions.prf:
/usr/local/share/qt/mkspecs/features/qt.prf:
/usr/local/share/qt/mkspecs/features/resources_functions.prf:
/usr/local/share/qt/mkspecs/features/resources.prf:
/usr/local/share/qt/mkspecs/features/moc.prf:
/usr/local/share/qt/mkspecs/features/unix/opengl.prf:
/usr/local/share/qt/mkspecs/features/uic.prf:
/usr/local/share/qt/mkspecs/features/unix/thread.prf:
/usr/local/share/qt/mkspecs/features/qmake_use.prf:
/usr/local/share/qt/mkspecs/features/file_copies.prf:
/usr/local/share/qt/mkspecs/features/mac/rez.prf:
/usr/local/share/qt/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/share/qt/mkspecs/features/testcase_targets.prf:
/usr/local/share/qt/mkspecs/features/exceptions.prf:
/usr/local/share/qt/mkspecs/features/yacc.prf:
/usr/local/share/qt/mkspecs/features/lex.prf:
Chess_Project.pro:
/usr/local/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/usr/local/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Chess_Project.pro

qmake_all: FORCE

build/Chess_Project.app/Contents/PkgInfo: 
	@test -d build/Chess_Project.app/Contents || mkdir -p build/Chess_Project.app/Contents
	@$(DEL_FILE) build/Chess_Project.app/Contents/PkgInfo
	@echo "APPL????" > build/Chess_Project.app/Contents/PkgInfo
build/Chess_Project.app/Contents/Info.plist: 
	@test -d build/Chess_Project.app/Contents || mkdir -p build/Chess_Project.app/Contents
	@$(DEL_FILE) build/Chess_Project.app/Contents/Info.plist
	@plutil -convert xml1 -o - /usr/local/share/qt/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,OneManArmy.Chess-Project,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},OneManArmy.Chess-Project,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},14.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Chess_Project,g" -e "s,@LIBRARY@,Chess_Project,g" -e "s,\$${EXECUTABLE_NAME},Chess_Project,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >build/Chess_Project.app/Contents/Info.plist

all: Makefile \
		build/Chess_Project.app/Contents/PkgInfo \
		build/Chess_Project.app/Contents/Info.plist build/Chess_Project.app/Contents/MacOS/Chess_Project

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/share/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/Case.h include/Cavalier.h include/Jeux.h include/Joueur.h include/Piece.h include/ProjetFinalEchec.h include/Roi.h include/Tour.h $(DISTDIR)/
	$(COPY_FILE) --parents src/Case.cpp src/Cavalier.cpp src/Jeux.cpp src/Joueur.cpp src/main.cpp src/Piece.cpp src/ProjetFinalEchec.cpp src/Roi.cpp src/Tour.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ProjetFinalEchec.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r build/Chess_Project.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc/moc_predefs.h
build/moc/moc_predefs.h: /usr/local/share/qt/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk -mmacosx-version-min=14.0 -Wall -Wextra -fPIC -dM -E -o build/moc/moc_predefs.h /usr/local/share/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc/moc_ProjetFinalEchec.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_ProjetFinalEchec.cpp
build/moc/moc_ProjetFinalEchec.cpp: include/ProjetFinalEchec.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		build/ui/ui_ProjetFinalEchec.h \
		include/Joueur.h \
		include/Piece.h \
		include/Case.h \
		include/Jeux.h \
		include/Cavalier.h \
		include/Roi.h \
		include/Tour.h \
		build/moc/moc_predefs.h \
		/usr/local/share/qt/libexec/moc
	/usr/local/share/qt/libexec/moc $(DEFINES) --include /Users/zakariazair/Desktop/personal_projects/qt_board_game/build/moc/moc_predefs.h -I/usr/local/share/qt/mkspecs/macx-clang -I/Users/zakariazair/Desktop/personal_projects/qt_board_game -I/Users/zakariazair/Desktop/personal_projects/qt_board_game -I/Users/zakariazair/Desktop/personal_projects/qt_board_game/include -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/lib include/ProjetFinalEchec.h -o build/moc/moc_ProjetFinalEchec.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui/ui_ProjetFinalEchec.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui/ui_ProjetFinalEchec.h
build/ui/ui_ProjetFinalEchec.h: ProjetFinalEchec.ui \
		/usr/local/share/qt/libexec/uic
	/usr/local/share/qt/libexec/uic ProjetFinalEchec.ui -o build/ui/ui_ProjetFinalEchec.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/objs/Case.o: src/Case.cpp include/Case.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objs/Case.o src/Case.cpp

build/objs/Cavalier.o: src/Cavalier.cpp include/Cavalier.h \
		include/Piece.h \
		include/Case.h \
		include/Jeux.h \
		include/Joueur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objs/Cavalier.o src/Cavalier.cpp

build/objs/Jeux.o: src/Jeux.cpp include/Jeux.h \
		include/Case.h \
		include/Piece.h \
		include/Joueur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objs/Jeux.o src/Jeux.cpp

build/objs/Joueur.o: src/Joueur.cpp include/Joueur.h \
		include/Piece.h \
		include/Case.h \
		include/Jeux.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objs/Joueur.o src/Joueur.cpp

build/objs/main.o: src/main.cpp include/ProjetFinalEchec.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		build/ui/ui_ProjetFinalEchec.h \
		include/Joueur.h \
		include/Piece.h \
		include/Case.h \
		include/Jeux.h \
		include/Cavalier.h \
		include/Roi.h \
		include/Tour.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objs/main.o src/main.cpp

build/objs/Piece.o: src/Piece.cpp include/Piece.h \
		include/Case.h \
		include/Jeux.h \
		include/Joueur.h \
		include/Cavalier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objs/Piece.o src/Piece.cpp

build/objs/ProjetFinalEchec.o: src/ProjetFinalEchec.cpp include/ProjetFinalEchec.h \
		/usr/local/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/lib/QtWidgets.framework/Headers/qlabel.h \
		build/ui/ui_ProjetFinalEchec.h \
		include/Joueur.h \
		include/Piece.h \
		include/Case.h \
		include/Jeux.h \
		include/Cavalier.h \
		include/Roi.h \
		include/Tour.h \
		/usr/local/lib/QtWidgets.framework/Headers/QFontComboBox \
		/usr/local/lib/QtWidgets.framework/Headers/qfontcombobox.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/usr/local/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/usr/local/lib/QtWidgets.framework/Headers/QButtonGroup \
		/usr/local/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		/usr/local/lib/QtWidgets.framework/Headers/QRadioButton \
		/usr/local/lib/QtWidgets.framework/Headers/qradiobutton.h \
		/usr/local/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/lib/QtWidgets.framework/Headers/QBoxLayout \
		/usr/local/lib/QtWidgets.framework/Headers/qboxlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objs/ProjetFinalEchec.o src/ProjetFinalEchec.cpp

build/objs/Roi.o: src/Roi.cpp include/Joueur.h \
		include/Piece.h \
		include/Case.h \
		include/Jeux.h \
		include/Roi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objs/Roi.o src/Roi.cpp

build/objs/Tour.o: src/Tour.cpp include/Joueur.h \
		include/Piece.h \
		include/Case.h \
		include/Jeux.h \
		include/Tour.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objs/Tour.o src/Tour.cpp

build/objs/moc_ProjetFinalEchec.o: build/moc/moc_ProjetFinalEchec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objs/moc_ProjetFinalEchec.o build/moc/moc_ProjetFinalEchec.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

